### ISSUE TITLE
Dutch abbreviation of Wednesday (and rest of the weekdays)

### ISSUE THREAD

**Issue by richardadvocaat** [davidtinker/intervals-i18n#162]
<img width="118" alt="weekdays" src="https://github.com/user-attachments/assets/53c73e9a-da50-4f70-abdd-735bc35d1788">

In the day of the week filter I mentioned some issues:

In the line the Dutch abbreviation of the day "woensdag" (= Wednesday) is translated to the Dutch verb trouwen (= to marry). The translation of the verb "to wed" is "trouwen".  

This fix should be:

  "Wed": "Trouwen",  -->  **"Wed": "Wo",** 

And the rest of the abbreviations of the weekdays are not consequent. My suggestion is to make them al 2-letter abbreviations:

"Mon": "Ma",
"Monday": "Maandag",
=OK

"Tues": "Dinsdag", --->   **"Tues": "Di",**
"Tuesday": "Dinsdag",

 "Wed": "Trouwen",   **"Wed": "Wo",** 
"Wednesday": "Woensdag",

"Thurs": "Donderdag", -->   **"Thurs": "Do",**
"Thursday": "Donderdag",

"Fri": "Vr",
"Friday": "Vrijdag", 
=OK

"Sat": "Za",
"Saturday": "Zaterdag",
=OK

"Sun": "Zon", -->  **"Sun": "Zo",**
"Sunday": "Zondag",

**Comment by davidtinker** [comment]
I have made those changes. Will deploy later today. Tx.
